name: build

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          # sudo snap install zig --classic --beta
          # go install github.com/crazy-max/xgo@latest

      - name: Build
        run: |
          bash build.sh release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: alist
          path: dist